applications/biblioteca/urls.py
from django.urls import include,path,re_path

from . import views


app_name = "biblioteca_app"

urlpatterns = [ 
    path("", views.ListaAutores.as_view() , name = "lista-autores"),
    path("libros-autor/<pk>/por-autor", views.ListaLibrosAutores.as_view() , name = "lista-libros"),
    path("autor/add", views.AddAutor.as_view() , name = "autor-add"),

]

applications/home/urls.py
from django.urls import include,path,re_path

from . import views


app_name = "home_app"

urlpatterns = [ 
    path("index", views.IndexView.as_view() , name = "index"),
    path ("libros", views.ListaLibros.as_view(), name = "lista")
]

libro/urls.py
from django.contrib import admin
from django.urls import path,include, re_path

urlpatterns = [
    re_path(r'^',include('applications.home.urls')), 
    re_path(r'^',include('applications.biblioteca.urls')), 
    path('admin/', admin.site.urls),
    ]

applications/biblioteca/models.py
from django.db import models

# Create your models here.

class Autor(models.Model):
    nombre = models.CharField("nombres", max_length=80)
    nacionalidad = models.CharField(blank=True, max_length=100)

    def __str__(self):
        return self.nombre

class Libros(models.Model):
    title = models.CharField("titulo", blank = False,max_length= 150)
    resume = models.TextField("Resumen", blank = True )
    autor = models.ForeignKey(Autor, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

applications/home/models.py
from django.db import models

# Create your models here.

applications/biblioteca/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import ( 
    TemplateView,
    ListView,
    CreateView,
    )
from .models import Autor, Libros
# Create your views here.



class ListaAutores(ListView):
    template_name = "biblioteca/lista-autores.html"
    model = Autor
    context_object_name = "autores"

# Lista libros por autoe
class ListaLibrosAutores(ListView):
    template_name = "biblioteca/lista-libros.html"
    context_object_name = "libros" 

    def get_queryset(self):
      
        # identificar el autor
        id = self.kwargs["pk"]
        
        # Filtro libros
        lista = Libros.objects.filter(
            autor = id
        )

        # Filtro por nacionalidad
        #nac = self.kwargs['nacionalidad']
        #lista = Libros.objects.filter(
        #    autor__nacionalidad = nac
        #)
        # Resultado
        return lista


class AddAutor(CreateView):
    """ vista para registrar un n uevo autor """
    template_name = "biblioteca/add-autor.html"
    model = Autor
    # que campos quiero que visite para que se pueda registrar
    fields = ["nombre","nacionalidad"] # Para validar otro tipo de fields que es distinto

    success_url = "/" # recarge la pagina que yo elija

applications/home/views.py
from django.shortcuts import render

from django.views.generic import ( 
    TemplateView,
    ListView,
    )
# Create your views here.

class IndexView(TemplateView):
    # una vista procesa los datos y renderiza el resultado en pantalla
    # siempre nos pedira un tempalate para trabajar
    # un template es un archivo html
    template_name = "home/index.html"


class ListaLibros(ListView):
    template_name = "home/lista.html"
    queryset = ["Harry Potter","El quijote","La que me dio un beso","Veamos lo que tengo","Django 2.0"]
    context_object_name = "libros"

templates/biblioteca/add-autor.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Agregar Autor</title>
    </head>
    <body>
        <h1>Agregar Autor</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit" name = "button">Pulsar para guardar</button>
        </form>
       
    </tbody>
                      
       
    </body>
</html>

templates/biblioteca/lista-autores.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Lista de autors</title>
    </head>
    <body>
        <h1>Autores registardos</h1>
        <table border="1">
            <thead>
                <th>Id</th>
                <th>Nombres</th>
                <th>Nacionalidad</th>
                <th>Accion</th>
            </thead>
            <tbody>
            
            {% for  a in autores %}
              <tr>
                <td>{{a.id}}</td> 
                <td>{{a.nombre}}</td> 
                <td>{{a.nacionalidad}}</td>
                <td><a href="{% url 'biblioteca_app:lista-libros' a.id %}">VER Libros</a></td>
              </tr>
            {% endfor %}
            </tbody>
            
            
        </table>
       
    </body>
</html>

templates/biblioteca/lista-libros.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Lista libros por autor</title>
    </head>
    <body>
        <h1>Lista libros Autor</h1>
        <table border="1">
            <thead>
                <th>Id</th>
                <th>Titulo</th>
                <th>Autor</th>
            </thead>
            <tbody>
            
            {% for  l in libros %}
              <tr>
                <td>{{l.id}}</td> 
                <td>{{l.title}}</td>
                <td>{{l.autor.nombre}}></td>
              </tr>
            {% endfor %}
            </tbody>
            
            
        </table>
       
    </body>
</html>

templates/home/index.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>mi primera vista en django</h1>
    </body>
</html>

templates/home/lista.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <h1>Lista de libros - probando vistas genericas</h1>
        {% for l in libros %}
        <p>{{ l }}</p>
        {% endfor %}
    </body>
</html>